language: python
python:
- '3.6'
services:
  - postgresql
before_script:
- pip3 install -r requirements.txt
- psql -c 'create database ahdb;' -U postgres
- python manage.py makemigrations
- python manage.py migrate
script:
- coverage run --source='authors' manage.py test
- coverage report